language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script: phpunit
before_install:
- openssl aes-256-cbc -K $encrypted_f7426f5c17e3_key -iv $encrypted_f7426f5c17e3_iv
  -in config.php.enc -out src/config/testing/config.php -d
